return {
    -- {
    --     "vhyrro/luarocks.nvim",
    --     name = "luarocks",
    --     priority = 1000,
    --     opts = {
    --         rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" },
    --     },
    -- },
    -- {
    --     "rest-nvim/rest.nvim",
    --     lazy = true,
    --     ft = "http",
    --     dependencies = { "luarocks" },
    --     config = function()
    --         require("rest-nvim").setup({
    --             skip_ssl_verification = true,
    --         })
    --     end,
    -- },
}
